package entity;
// Generated 8/12/2017 12:27:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Esquema generated by hbm2java
 */
public class Esquema  implements java.io.Serializable {


     private String nombre;
     private String cadena;
     private Set grupos = new HashSet(0);

    public Esquema() {
    }

	
    public Esquema(String nombre, String cadena) {
        this.nombre = nombre;
        this.cadena = cadena;
    }
    public Esquema(String nombre, String cadena, Set grupos) {
       this.nombre = nombre;
       this.cadena = cadena;
       this.grupos = grupos;
    }
   
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCadena() {
        return this.cadena;
    }
    
    public void setCadena(String cadena) {
        this.cadena = cadena;
    }
    public Set getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Set grupos) {
        this.grupos = grupos;
    }




}


