package entity;
// Generated 8/12/2017 12:27:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer user;
     private String nombre;
     private String apellido;
     private String pass;
     private int tipo;
     private Set grupos = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(String nombre, int tipo) {
        this.nombre = nombre;
        this.tipo = tipo;
    }
    public Usuarios(String nombre, String apellido, String pass, int tipo, Set grupos) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.pass = pass;
       this.tipo = tipo;
       this.grupos = grupos;
    }
   
    public Integer getUser() {
        return this.user;
    }
    
    public void setUser(Integer user) {
        this.user = user;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public int getTipo() {
        return this.tipo;
    }
    
    public void setTipo(int tipo) {
        this.tipo = tipo;
    }
    public Set getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Set grupos) {
        this.grupos = grupos;
    }




}


